"""empty message

Revision ID: 86f2a9f7f754
Revises: 
Create Date: 2025-06-12 21:32:52.900634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f2a9f7f754'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('adminId', sa.Integer(), nullable=False),
    sa.Column('adminName', sa.String(length=50), nullable=False),
    sa.Column('adminEmail', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('adminId')
    )
    op.create_table('categories',
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.Column('categoryName', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('categoryId')
    )
    op.create_table('collaborator',
    sa.Column('collaboratorId', sa.Integer(), nullable=False),
    sa.Column('collaboratorName', sa.String(length=50), nullable=False),
    sa.Column('collaboratorEmail', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('collaboratorId')
    )
    op.create_table('pages',
    sa.Column('pageId', sa.Integer(), nullable=False),
    sa.Column('pageName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('pageId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    op.drop_table('collaborator')
    op.drop_table('categories')
    op.drop_table('admins')
    # ### end Alembic commands ###
