"""empty message

Revision ID: a702d5cbb66b
Revises: 86f2a9f7f754
Create Date: 2025-06-19 19:08:35.570928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a702d5cbb66b'
down_revision = '86f2a9f7f754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_category_association',
    sa.Column('collaboratorId', sa.Integer(), nullable=False),
    sa.Column('categoryId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['categories.categoryId'], ),
    sa.ForeignKeyConstraint(['collaboratorId'], ['collaborator.collaboratorId'], ),
    sa.PrimaryKeyConstraint('collaboratorId', 'categoryId')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoryId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collaboratorId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'collaborator', ['collaboratorId'], ['collaboratorId'])
        batch_op.create_foreign_key(None, 'categories', ['categoryId'], ['categoryId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('collaboratorId')
        batch_op.drop_column('categoryId')

    op.drop_table('collaborator_category_association')
    # ### end Alembic commands ###
